using System.Collections.Generic;
using System.Linq;
using System.Reflection;

namespace HeroesReplay.Shared
{
    public static class Heroes
    {
        public static Hero Abathur = new Hero("Abathur", HeroType.Melee);
        public static Hero Alarak = new Hero("Alarak", HeroType.Melee);
        public static Hero Alexstrasza = new Hero("Alexstrasza", HeroType.Ranged);
        public static Hero Amazon = new Hero("Amazon", HeroType.Ranged);
        public static Hero Ana = new Hero("Ana", HeroType.Ranged);
        public static Hero Anduin = new Hero("Anduin", HeroType.Ranged);
        public static Hero Anubarak = new Hero("Anubarak", HeroType.Melee);
        public static Hero Artanis = new Hero("Artanis", HeroType.Melee);
        public static Hero Arthas = new Hero("Arthas", HeroType.Melee);
        public static Hero Auriel = new Hero("Auriel", HeroType.Ranged);
        public static Hero Azmodan = new Hero("Azmodan", HeroType.Ranged);
        public static Hero Barbarian = new Hero("Barbarian", HeroType.Melee);
        public static Hero Butcher = new Hero("Butcher", HeroType.Melee);
        public static Hero Chen = new Hero("Chen", HeroType.Melee);
        public static Hero Cho = new Hero("Cho", HeroType.Melee);
        public static Hero Chromie = new Hero("Chromie", HeroType.Ranged);
        public static Hero Crusader = new Hero("Crusader", HeroType.Melee);
        public static Hero Deathwing = new Hero("Deathwing", HeroType.Melee);
        public static Hero Deckard = new Hero("Deckard", HeroType.Melee);
        public static Hero Dehaka = new Hero("Dehaka", HeroType.Melee);
        public static Hero DemonHunter = new Hero("DemonHunter", HeroType.Ranged);
        public static Hero Diablo = new Hero("Diablo", HeroType.Melee);
        public static Hero Dryad = new Hero("Dryad", HeroType.Ranged);
        public static Hero DVa = new Hero("DVa", HeroType.Ranged);
        public static Hero FaerieDragon = new Hero("FaerieDragon", HeroType.Ranged);
        public static Hero Falstad = new Hero("Falstad", HeroType.Ranged);
        public static Hero Fenix = new Hero("Fenix", HeroType.Ranged);
        public static Hero Firebat = new Hero("Firebat", HeroType.Ranged);
        public static Hero Gall = new Hero("Gall", HeroType.Ranged);
        public static Hero Garrosh = new Hero("Garrosh", HeroType.Melee);
        public static Hero Genji = new Hero("Genji", HeroType.Ranged);
        public static Hero Greymane = new Hero("Greymane", HeroType.Ranged);
        public static Hero Guldan = new Hero("Guldan", HeroType.Ranged);
        public static Hero Hanzo = new Hero("Hanzo", HeroType.Ranged);
        public static Hero Illidan = new Hero("Illidan", HeroType.Melee);
        public static Hero Imperius = new Hero("Imperius", HeroType.Melee);
        public static Hero Jaina = new Hero("Jaina", HeroType.Ranged);
        public static Hero Junkrat = new Hero("Junkrat", HeroType.Ranged);
        public static Hero Kaelthas = new Hero("Kaelthas", HeroType.Ranged);
        public static Hero KelThuzad = new Hero("KelThuzad", HeroType.Ranged);
        public static Hero Kerrigan = new Hero("Kerrigan", HeroType.Melee);
        public static Hero L90ETC = new Hero("L90ETC", HeroType.Melee);
        public static Hero Leoric = new Hero("Leoric", HeroType.Melee);
        public static Hero LiLi = new Hero("LiLi", HeroType.Ranged);
        public static Hero LostVikings = new Hero("LostVikings", HeroType.Melee);
        public static Hero Lucio = new Hero("Lucio", HeroType.Ranged);
        public static Hero Maiev = new Hero("Maiev", HeroType.Melee);
        public static Hero Malfurion = new Hero("Malfurion", HeroType.Ranged);
        public static Hero MalGanis = new Hero("MalGanis", HeroType.Melee);
        public static Hero Malthael = new Hero("Malthael", HeroType.Melee);
        public static Hero Medic = new Hero("Medic", HeroType.Ranged);
        public static Hero Medivh = new Hero("Medivh", HeroType.Ranged);
        public static Hero Mephisto = new Hero("Mephisto", HeroType.Ranged);
        public static Hero Monk = new Hero("Monk", HeroType.Melee);
        public static Hero Muradin = new Hero("Muradin", HeroType.Melee);
        public static Hero Murky = new Hero("Murky", HeroType.Melee);
        public static Hero Necromancer = new Hero("Necromancer", HeroType.Melee);
        public static Hero NexusHunter = new Hero("NexusHunter", HeroType.Ranged);
        public static Hero Nova = new Hero("Nova", HeroType.Ranged);
        public static Hero Orphea = new Hero("Orphea", HeroType.Ranged);
        public static Hero Probius = new Hero("Probius", HeroType.Ranged);
        public static Hero Ragnaros = new Hero("Ragnaros", HeroType.Melee);
        public static Hero Raynor = new Hero("Raynor", HeroType.Ranged);
        public static Hero Rehgar = new Hero("Rehgar", HeroType.Melee);
        public static Hero Rexxar = new Hero("Rexxar", HeroType.Ranged);
        public static Hero Samuro = new Hero("Samuro", HeroType.Melee);
        public static Hero SgtHammer = new Hero("SgtHammer", HeroType.Ranged);
        public static Hero Stitches = new Hero("Stitches", HeroType.Melee);
        public static Hero Stukov = new Hero("Stukov", HeroType.Melee);
        public static Hero Sylvanas = new Hero("Sylvanas", HeroType.Ranged);
        public static Hero Tassadar = new Hero("Tassadar", HeroType.Ranged);
        public static Hero Thrall = new Hero("Thrall", HeroType.Melee);
        public static Hero Tinker = new Hero("Tinker", HeroType.Melee);
        public static Hero Tracer = new Hero("Tracer", HeroType.Ranged);
        public static Hero Tychus = new Hero("Tychus", HeroType.Ranged);
        public static Hero Tyrael = new Hero("Tyrael", HeroType.Melee);
        public static Hero Tyrande = new Hero("Tyrande", HeroType.Ranged);
        public static Hero Uther = new Hero("Uther", HeroType.Melee);
        public static Hero Valeera = new Hero("Valeera", HeroType.Melee);
        public static Hero Varian = new Hero("Varian", HeroType.Melee);
        public static Hero Whitemane = new Hero("Whitemane", HeroType.Ranged);
        public static Hero WitchDoctor = new Hero("WitchDoctor", HeroType.Ranged);
        public static Hero Wizard = new Hero("Wizard", HeroType.Ranged);
        public static Hero Yrel = new Hero("Yrel", HeroType.Melee);
        public static Hero Zagara = new Hero("Zagara", HeroType.Ranged);
        public static Hero Zarya = new Hero("Zarya", HeroType.Ranged);
        public static Hero Zeratul = new Hero("Zeratul", HeroType.Melee);
        public static Hero Zuljin = new Hero("Zuljin", HeroType.Ranged);
    }
}
