<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <StartupObject />
        <AssemblyName>heroesreplay</AssemblyName>
        <IsPackable>false</IsPackable>
        <ApplicationIcon>heroesreplay.ico</ApplicationIcon>
        <UseWindowsForms>true</UseWindowsForms>
        <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Http" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" />
        <PackageReference Include="Microsoft.Extensions.Logging.EventLog" />
        <PackageReference Include="System.CommandLine" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HeroesReplay.Core\HeroesReplay.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.dev.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="appsettings.prod.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="appsettings.secrets.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Assets\Maps.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
