<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <UseWindowsForms>true</UseWindowsForms>
        <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.Core" />
        <PackageReference Include="AWSSDK.S3" />
        <PackageReference Include="Google.Apis.YouTube.v3" />
        <PackageReference Include="Heroes.ReplayParser" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
        <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Http" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Options" />
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="obs-websocket-dotnet" />
        <PackageReference Include="PInvoke.User32" />
        <PackageReference Include="Polly" />
        <PackageReference Include="Polly.Caching.Memory" />
        <PackageReference Include="TwitchLib" />
    </ItemGroup>
</Project>
